# Generated by Django 2.1.5 on 2020-07-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d'),
        ),
    ]
